spring.application.name=todo-list-spring
server.port=8080

spring.datasource.url=jdbc:mariadb://172.16.226.143/bdtareas
spring.datasource.username=batoi
spring.datasource.password=2002ricardo
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver